### ISSUE TITLE
SFOS 3.3.0.14/16 - dependency on libgcrypt.so.11

### ISSUE THREAD

**Issue by cy8aer** [rinigus/collectd#10]
*   Version of collectd: 5.5.0.git-2020.04.29-1.19.1.jolla
*   Operating system / distribution: SFOS 3.3.0.16

## Expected behavior

It installs from openrepos

## Actual behavior

Install error (german):

Nichts stellt libgcrypt.so.11 bereit, welches von collectd... benötigt wird
(libgcrypt.so.11 needed but not available).

With upgrading to 3.3.0.14 collectd and SystemDataScope was uninstalled.
3.3.0.14 upgrades to libgcrypt.so.20

## Steps to reproduce

* just try to install from Storeman...

**Comment by cy8aer** [comment]
next SDK for 3.3.0.16 needed... But then there is an incompatibility to older SFOS versions...

**Comment by rinigus** [comment]
So that's why collectd was uninstalled. As OBS still does not have 3.3 targets, I will deal with it later. I wonder which plugin requires gcrypt, maybe its not used in practice...

**Comment by cy8aer** [comment]
this may be used for tls communication with remote systems:

- influxdb
- https connections
- ...

**Comment by rinigus** [comment]
New build of collectd is available at OBS. As I don't have my device updated yet, would you mind to test if it works now? As far as I can see, libgcrypt dependency was updated. 

OBS project: https://build.merproject.org/project/show/home:rinigus:sds

**Comment by cy8aer** [comment]
Hi Rinigus,
it installs, starts and works (together with SystemDataScope)

**Comment by rinigus** [comment]
Hi! Thank you very much, fixed package is released at OpenRepos. Closing it here
