### ISSUE TITLE
swap.so is missing in SailfishOS package

### ISSUE THREAD

**Issue by Self-Perfection** [rinigus/collectd#5]
*   Version of collectd: 5.5.0.git.2016.09.19
*   Operating system / distribution: SailfishOS 2.1.3.7

## Expected behavior

Collectd should be able to monitor swap free/used space

## Actual behavior

(Description of the behavior / output that you observed)

## Steps to reproduce

*   Uncomment `LoadPlugin swap` in `/etc/collectd.conf`
*   Restart collectd
*   It does not load complaining about incorrect config

**Comment by rinigus** [comment]
Indeed, swap plugin is not enabled, see https://github.com/rinigus/collectd/blob/sailfish/contrib/sailfish/collectd.spec#L220. I presume that you have swap on your device since I don't think its common. I don't mind enabling it. Then, in addition, we'll need visualization of graphs via SystemDataScope, right?

**Comment by Self-Perfection** [comment]
@rinigus Why do you suppose that enabled swap is not common? I have Jolla one and Jolla C and both devices use swap out of the box. It can be easy checked by running `swapon -s`

> Then, in addition, we'll need visualization of graphs via SystemDataScope, right?

That is correct. But does this visualization need special handling? I assumed running "Generate definitions" from settings should be enough.

**Comment by rinigus** [comment]
I have used ported devices so far and the ones that I have don't enable swap. But its no biggie, I don't mind adding it. And thanks for sending in the issue - its a best way to get it on.

As for graphs, I will have to check whether the generating script has to be adjusted. 

I'll take a look into it.

**Comment by rinigus** [comment]
I have a new test version out at http://repo.merproject.org/obs/home:/rinigus:/sds/sailfish_latest_armv7hl/armv7hl/ . Please test with SystemDataScope and collectd from there. If you modified /etc/collectd.conf, it will not be altered, as far as I know. You would have to enable swap module yourself then (see /etc/collectd.conf.rpmsave and rpmnew). 

Please let me know whether it all works. On my device there is no swap, so its tested on PC only.

**Comment by rinigus** [comment]
Just updated it again and moved swap graphs under memory details. This should be a reasonable location for all devices , I think

**Comment by Self-Perfection** [comment]
Just tested it on Jolla C and swap monitoring works flawlessly. Cool, thank you!

**Comment by rinigus** [comment]
Thank you for testing. Closing
